# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sreyan Ghosh
full_name: Sreyan Ghosh
email: gsreyan@gmail.com
email2: sreyan.ghosh@tech.christuniversity.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://martiansideofthemoon.github.io" # the base hostname & protocol for your site
github_username:  Sreyan88
twitter_username: kalpeshk2011
linkedin_username: sreyan-ghosh
# stackoverflow: 5080995/martianwars
include: ['_pages']
# footer-links-active:
#   stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
