# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Last Martian
email: kalpeshk2011@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://martiansideofthemoon.github.io" # the base hostname & protocol for your site
github_username:  martiansideofthemoon
twitter_username: kalpeshk2011
stackoverflow: 5080995/martianwars

footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-twitter-plugin
